export default [
  [
    { code: "KeyE", value: "E" },
    { code: "KeyR", value: "R" },
    { code: "KeyT", value: "T" },
    { code: "KeyY", value: "Y" },
    { code: "KeyU", value: "U" },
    { code: "KeyI", value: "I" },
    { code: "KeyO", value: "O" },
    { code: "KeyP", value: "P" },
    { code: "BracketLeft", value: "Ğ" },
    { code: "BracketRight", value: "Ü" },
  ],
  [
    { code: "KeyA", value: "A" },
    { code: "KeyS", value: "S" },
    { code: "KeyD", value: "D" },
    { code: "KeyF", value: "F" },
    { code: "KeyG", value: "G" },
    { code: "KeyH", value: "H" },
    { code: "KeyJ", value: "J" },
    { code: "KeyK", value: "K" },
    { code: "KeyL", value: "L" },
    { code: "Semicolon", value: "Ş" },
    { code: "Quote", value: "İ" },
  ],
  [
    { code: "Enter", value: "ENTER" },
    { code: "KeyZ", value: "Z" },
    { code: "KeyX", value: "X" },
    { code: "KeyC", value: "C" },
    { code: "KeyV", value: "V" },
    { code: "KeyB", value: "B" },
    { code: "KeyN", value: "N" },
    { code: "KeyM", value: "M" },
    { code: "Comma", value: "Ö" },
    { code: "Period", value: "Ç" },
    { code: "Backspace", value: "BACKSPACE" },
  ],
];
